modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/yori3o/BossChecklist/issues"
logoFile = "logo.png"
license = "MIT Licence"

[[mods]]
modId = "boss_checklist"
version = "${version}"
displayName = "Boss Checklist"
authors = "Yori3o"
description = '''
Adds a convenient list of bosses to the game with brief information about them.
'''
displayURL="https://modrinth.com/mod/boss-checklist"

[[dependencies.boss_checklist]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boss_checklist]]
modId = "minecraft"
type = "required"
versionRange = "1.21.1"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "boss_checklist.mixins.json"
