modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
logoFile = "logo.png"
license = "CC BY-NC 4.0"

[[mods]]
modId = "boss_checklist"
version = "${version}"
displayName = "Boss Checklist"
authors = "Yori3o"
description = '''
Adds a convenient list of bosses to the game with brief information about them.
'''

[[dependencies.boss_checklist]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boss_checklist]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boss_checklist]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "boss_checklist.mixins.json"
